import { useEffect, useState, useRef, useCallback } from 'react';
import { supabase } from '../../lib/supabase';
import { useAuthStore } from '../../store/authStore';

// ─── Icon mapping ─────────────────────────────────────────────────────────────
const ICON_MAP = [
  [/ชีสเค้ก|cheese\s*cake/i,        '🍰', '#FEF9C3'],
  [/ช็อค|chocolate|โกโก้/i,         '🍫', '#FEF3C7'],
  [/มัฟฟิน|muffin/i,                '🧁', '#FCE7F3'],
  [/คุกกี้|cookie/i,                '🍪', '#FFF7ED'],
  [/ครัวซอง|croissant/i,            '🥐', '#FEF3C7'],
  [/ทาร์ต|tart/i,                   '🥧', '#FEF9C3'],
  [/มาการอง|macaron/i,              '💜', '#EDE9FE'],
  [/บราวนี่|brownie/i,              '🟫', '#FEF3C7'],
  [/วาฟเฟิล|waffle/i,               '🧇', '#FEF9C3'],
  [/ขนมปัง|bread|บาแก็ต/i,         '🥖', '#FEF9C3'],
  [/มาชา|matcha/i,                  '🍵', '#ECFDF5'],
  [/สตรอว์|strawberry/i,            '🍓', '#FFF0F0'],
  [/เลมอน|lemon/i,                  '🍋', '#FEFCE8'],
  [/พาย|pie/i,                      '🥧', '#FEF9C3'],
  [/โรล|roll|ม้วน/i,                '🌀', '#F0F9FF'],
  [/เค้ก|cake/i,                    '🎂', '#FCE7F3'],
];

function getIcon(name) {
  for (const [re, icon] of ICON_MAP) if (re.test(name)) return icon;
  return '🍞';
}
function getBg(name) {
  for (const [re, , bg] of ICON_MAP) if (re.test(name)) return bg;
  return '#F9FAFB';
}

// ─── Canvas Export ────────────────────────────────────────────────────────────
function drawExport(canvas, { items, stockMap, branchName, empName }) {
  const W = 800;
  const LINE_H = 46;
  const HEADER_H = 160;
  const FOOTER_H = 72;
  const H = HEADER_H + LINE_H + items.length * LINE_H + FOOTER_H;
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d');
  const F = (size, bold) => `${bold ? 'bold ' : ''}${size}px "Sarabun","Tahoma","Arial",sans-serif`;

  ctx.fillStyle = '#FFFFFF';
  ctx.fillRect(0, 0, W, H);

  // Header strip
  ctx.fillStyle = '#4A2E1A';
  ctx.fillRect(0, 0, W, 100);

  ctx.fillStyle = '#E8C89E';
  ctx.font = F(28, true);
  ctx.textAlign = 'center';
  ctx.fillText('☕ JE BAR Coffee & Pastry', W / 2, 38);
  ctx.fillStyle = '#FFFFFF';
  ctx.font = F(20, true);
  ctx.fillText('ใบเช็คสต็อคขนม', W / 2, 68);
  ctx.font = F(14);
  const dateStr = new Date().toLocaleDateString('th-TH', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' });
  ctx.fillText(`${dateStr}  |  สาขา: ${branchName}  |  ผู้เช็ค: ${empName}`, W / 2, 92);

  // Sub-header bar
  ctx.fillStyle = '#F9F5F0';
  ctx.fillRect(0, 100, W, 60);
  ctx.fillStyle = '#6B4226';
  ctx.font = F(13);
  ctx.textAlign = 'left';
  const openCount = items.filter(i => (stockMap[i.id] || 0) > 0).length;
  ctx.fillText(`รายการทั้งหมด: ${items.length} รายการ  |  มีสินค้า: ${openCount} รายการ  |  ไม่มีสินค้า: ${items.length - openCount} รายการ`, 32, 136);

  // Table header
  const y0 = HEADER_H;
  ctx.fillStyle = '#4A2E1A';
  ctx.fillRect(0, y0, W, LINE_H);
  ctx.fillStyle = '#FFFFFF';
  ctx.font = F(14, true);
  ctx.textAlign = 'left';
  ctx.fillText('#', 24, y0 + 30);
  ctx.fillText('รายการขนม', 68, y0 + 30);
  ctx.textAlign = 'right';
  ctx.fillText('จำนวน (ชิ้น)', W - 32, y0 + 30);

  // Rows
  items.forEach((item, idx) => {
    const ry = y0 + LINE_H + idx * LINE_H;
    const qty = stockMap[item.id] || 0;
    ctx.fillStyle = idx % 2 === 0 ? '#FFFFFF' : '#FAF7F3';
    ctx.fillRect(0, ry, W, LINE_H);

    // Divider
    ctx.strokeStyle = '#E5DDD5';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(0, ry + LINE_H - 0.5);
    ctx.lineTo(W, ry + LINE_H - 0.5);
    ctx.stroke();

    // Row number
    ctx.fillStyle = '#9CA3AF';
    ctx.font = F(13);
    ctx.textAlign = 'left';
    ctx.fillText(String(idx + 1), 24, ry + 30);

    // Item name
    ctx.fillStyle = '#1F2937';
    ctx.font = F(15, true);
    ctx.fillText(`${getIcon(item.name)}  ${item.name}`, 68, ry + 30);

    // Qty
    ctx.textAlign = 'right';
    if (qty > 0) {
      ctx.fillStyle = '#166534';
      ctx.font = F(18, true);
    } else {
      ctx.fillStyle = '#9CA3AF';
      ctx.font = F(15);
    }
    ctx.fillText(qty > 0 ? String(qty) : '—', W - 32, ry + 30);
  });

  // Footer
  const fy = y0 + LINE_H + items.length * LINE_H;
  ctx.fillStyle = '#4A2E1A';
  ctx.fillRect(0, fy, W, FOOTER_H);
  ctx.fillStyle = '#E8C89E';
  ctx.font = F(13, true);
  ctx.textAlign = 'center';
  const totalQty = items.reduce((s, i) => s + (stockMap[i.id] || 0), 0);
  ctx.fillText(`รวม ${totalQty} ชิ้น  |  Generated by LUCID HR · JE BAR`, W / 2, fy + 42);
}

async function exportToImage({ items, stockMap, branchName, empName }) {
  const canvas = document.createElement('canvas');
  drawExport(canvas, { items, stockMap, branchName, empName });
  return new Promise(resolve => canvas.toBlob(resolve, 'image/png'));
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function fmtTime(ts) {
  const d = new Date(ts);
  return d.toLocaleString('th-TH', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

const ACTION_LABELS = {
  adjust: 'ปรับจำนวน',
  open: 'เปิดขาย',
  close: 'ปิดขาย',
  request_add: 'ขอเพิ่มรายการ',
  request_delete: 'ขอลบรายการ',
  approve: 'อนุมัติ',
  reject: 'ปฏิเสธ',
  reorder: 'เรียงลำดับ',
};

// ─── Main Component ───────────────────────────────────────────────────────────
export default function CakeStockPage({ navigate }) {
  const { employee } = useAuthStore();
  const myBranchId = employee?.branch_id;
  const empId = employee?.id;
  const empName = employee?.nickname || employee?.name || 'พนักงาน';
  const orgId = employee?.org_id;

  const [branches, setBranches] = useState([]);
  const [activeBranchId, setActiveBranchId] = useState(myBranchId || null);
  const [items, setItems] = useState([]);       // cake_items (active)
  const [stockMap, setStockMap] = useState({}); // { item_id: qty }
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(null);

  // Modals
  const [showHistory, setShowHistory] = useState(false);
  const [logs, setLogs] = useState([]);
  const [logsLoading, setLogsLoading] = useState(false);
  const [showRequestAdd, setShowRequestAdd] = useState(false);
  const [requestName, setRequestName] = useState('');
  const [requestSending, setRequestSending] = useState(false);

  // Drag-to-reorder
  const dragItem = useRef(null);
  const dragOver = useRef(null);

  // Load branches
  useEffect(() => {
    if (!orgId) return;
    supabase.from('branches').select('id,label').eq('org_id', orgId).order('label')
      .then(({ data }) => {
        if (data) setBranches(data);
      });
  }, [orgId]);

  // Set default tab to own branch once branches loaded
  useEffect(() => {
    if (branches.length && !activeBranchId) {
      setActiveBranchId(myBranchId || branches[0]?.id);
    }
  }, [branches, myBranchId, activeBranchId]);

  // Load items + stock for active branch
  const load = useCallback(async () => {
    if (!orgId || !activeBranchId) return;
    setLoading(true);
    try {
      const [{ data: itemData }, { data: stockData }] = await Promise.all([
        supabase.from('cake_items')
          .select('id,name,sort_order,is_open,status')
          .eq('org_id', orgId)
          .in('status', ['active'])
          .order('sort_order'),
        supabase.from('cake_stock')
          .select('item_id,qty')
          .eq('org_id', orgId)
          .eq('branch_id', activeBranchId),
      ]);
      if (itemData) setItems(itemData);
      if (stockData) {
        const m = {};
        stockData.forEach(r => { m[r.item_id] = r.qty; });
        setStockMap(m);
      }
    } finally {
      setLoading(false);
    }
  }, [orgId, activeBranchId]);

  useEffect(() => { load(); }, [load]);

  // isMyBranch: true if on own branch, OR if employee has no branch_id set (can edit any)
  const isMyBranch = !myBranchId || activeBranchId === myBranchId;

  // Write a log event
  async function writeLog(itemId, itemName, action, delta, qtyAfter, note) {
    await supabase.from('cake_stock_log').insert({
      org_id: orgId,
      branch_id: activeBranchId,
      item_id: itemId,
      item_name: itemName,
      emp_id: empId,
      emp_name: empName,
      action,
      delta,
      qty_after: qtyAfter,
      note,
    });
  }

  // Adjust qty (upsert into cake_stock)
  async function adjustQty(item, delta) {
    if (!isMyBranch) return;
    const prev = stockMap[item.id] || 0;
    const next = Math.max(0, prev + delta);
    setSaving(item.id);
    const newMap = { ...stockMap, [item.id]: next };
    setStockMap(newMap);
    try {
      await supabase.from('cake_stock').upsert({
        org_id: orgId,
        branch_id: activeBranchId,
        item_id: item.id,
        qty: next,
        updated_by: empId,
        updated_at: new Date().toISOString(),
      }, { onConflict: 'branch_id,item_id' });
      await writeLog(item.id, item.name, 'adjust', delta, next, null);
    } catch {
      setStockMap(prev => ({ ...prev, [item.id]: prev }));
    } finally {
      setSaving(null);
    }
  }

  // Toggle open/close (is_open) — only own branch context, but is_open is global per item
  // Only admin can do this; employees see toggle but request goes through
  // For simplicity: update is_open directly (admin-like), per approved design
  async function toggleOpen(item) {
    const newOpen = !item.is_open;
    setItems(prev => prev.map(i => i.id === item.id ? { ...i, is_open: newOpen } : i));
    await supabase.from('cake_items').update({ is_open: newOpen, updated_at: new Date().toISOString() }).eq('id', item.id);
    await writeLog(item.id, item.name, newOpen ? 'open' : 'close', null, null, null);
  }

  // Auto-sort: open items first
  async function autoSort() {
    const sorted = [
      ...items.filter(i => i.is_open),
      ...items.filter(i => !i.is_open),
    ].map((item, idx) => ({ ...item, sort_order: idx }));
    setItems(sorted);
    await Promise.all(
      sorted.map(item => supabase.from('cake_items').update({ sort_order: item.sort_order }).eq('id', item.id))
    );
    await writeLog(null, 'ทั้งหมด', 'reorder', null, null, 'auto-sort');
  }

  // Drag handlers
  function onDragStart(idx) { dragItem.current = idx; }
  function onDragEnter(idx) { dragOver.current = idx; }
  function onDragEnd() {
    if (dragItem.current === null || dragOver.current === null) return;
    const newItems = [...items];
    const [moved] = newItems.splice(dragItem.current, 1);
    newItems.splice(dragOver.current, 0, moved);
    dragItem.current = null;
    dragOver.current = null;
    const updated = newItems.map((item, idx) => ({ ...item, sort_order: idx }));
    setItems(updated);
    Promise.all(
      updated.map(item => supabase.from('cake_items').update({ sort_order: item.sort_order }).eq('id', item.id))
    ).then(() => writeLog(null, 'ทั้งหมด', 'reorder', null, null, 'drag'));
  }

  // Touch drag state
  const touchDragIdx = useRef(null);

  function onTouchStart(e, idx) {
    touchDragIdx.current = idx;
    e.currentTarget.style.opacity = '0.5';
  }
  function onTouchMove(e) {
    e.preventDefault();
    const touch = e.touches[0];
    const el = document.elementFromPoint(touch.clientX, touch.clientY);
    const row = el?.closest('[data-drag-idx]');
    if (row) dragOver.current = parseInt(row.dataset.dragIdx);
  }
  function onTouchEnd(e, idx) {
    e.currentTarget.style.opacity = '1';
    dragItem.current = touchDragIdx.current;
    onDragEnd();
    touchDragIdx.current = null;
  }

  // Request to add item
  async function submitRequestAdd() {
    if (!requestName.trim()) return;
    setRequestSending(true);
    try {
      await supabase.from('cake_items').insert({
        org_id: orgId,
        name: requestName.trim(),
        sort_order: 9999,
        is_open: true,
        status: 'pending_add',
        requested_by: empId,
      });
      await writeLog(null, requestName.trim(), 'request_add', null, null, `ขอเพิ่มโดย ${empName}`);
      setShowRequestAdd(false);
      setRequestName('');
      alert('ส่งคำขอแล้ว รอแอดมินอนุมัติ');
    } finally {
      setRequestSending(false);
    }
  }

  // Load history log
  async function openHistory() {
    setShowHistory(true);
    setLogsLoading(true);
    const cutoff = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
    const { data } = await supabase.from('cake_stock_log')
      .select('*')
      .eq('org_id', orgId)
      .eq('branch_id', activeBranchId)
      .gte('created_at', cutoff)
      .order('created_at', { ascending: false })
      .limit(200);
    setLogs(data || []);
    setLogsLoading(false);
  }

  // Export image
  async function handleExport() {
    const activeBranch = branches.find(b => b.id === activeBranchId);
    const branchName = activeBranch?.label || 'ไม่ระบุสาขา';
    const blob = await exportToImage({ items, stockMap, branchName, empName });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cake-stock-${branchName}-${new Date().toISOString().slice(0, 10)}.png`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const totalQty = items.reduce((s, i) => s + (stockMap[i.id] || 0), 0);
  const openCount = items.filter(i => (stockMap[i.id] || 0) > 0).length;

  // ─── Render ────────────────────────────────────────────────────────────────
  return (
    <div style={{ minHeight: '100vh', background: '#F9F5F0', fontFamily: '"Sarabun","Noto Sans Thai",sans-serif' }}>
      {/* Top bar */}
      <div style={{ background: '#4A2E1A', color: '#fff', padding: '14px 16px', display: 'flex', alignItems: 'center', gap: 10, position: 'sticky', top: 0, zIndex: 50 }}>
        <button onClick={() => navigate('/emp/ops')} style={{ background: 'none', border: 'none', color: '#E8C89E', fontSize: 22, cursor: 'pointer', padding: '0 4px' }}>←</button>
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 700, fontSize: 17 }}>🍰 เช็คสต็อคขนม</div>
          <div style={{ fontSize: 12, opacity: 0.75 }}>{isMyBranch ? 'สาขาของคุณ — แก้ไขได้' : 'ดูข้อมูลเท่านั้น'}</div>
        </div>
        <button onClick={openHistory} style={{ background: 'rgba(255,255,255,0.15)', border: 'none', color: '#fff', borderRadius: 8, padding: '6px 12px', fontSize: 13, cursor: 'pointer' }}>📋 ประวัติ</button>
        <button onClick={handleExport} style={{ background: '#E8C89E', border: 'none', color: '#4A2E1A', borderRadius: 8, padding: '6px 12px', fontSize: 13, fontWeight: 700, cursor: 'pointer' }}>📤 Export</button>
      </div>

      {/* Branch tabs */}
      {branches.length > 1 && (
        <div style={{ background: '#fff', borderBottom: '1px solid #E5DDD5', overflowX: 'auto', display: 'flex', padding: '0 8px' }}>
          {branches.map(b => (
            <button
              key={b.id}
              onClick={() => setActiveBranchId(b.id)}
              style={{
                whiteSpace: 'nowrap', padding: '12px 16px', border: 'none', cursor: 'pointer', fontSize: 14, fontWeight: b.id === activeBranchId ? 700 : 400,
                color: b.id === activeBranchId ? '#4A2E1A' : '#6B7280',
                background: 'none',
                borderBottom: b.id === activeBranchId ? '2px solid #4A2E1A' : '2px solid transparent',
              }}
            >
              {b.id === myBranchId ? '⭐ ' : ''}{b.label}
            </button>
          ))}
        </div>
      )}

      {/* Summary bar */}
      <div style={{ background: '#fff', padding: '12px 16px', display: 'flex', gap: 16, borderBottom: '1px solid #E5DDD5' }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 22, fontWeight: 700, color: '#4A2E1A' }}>{totalQty}</div>
          <div style={{ fontSize: 11, color: '#9CA3AF' }}>รวมทั้งหมด</div>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 22, fontWeight: 700, color: '#16A34A' }}>{openCount}</div>
          <div style={{ fontSize: 11, color: '#9CA3AF' }}>รายการมีสินค้า</div>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 22, fontWeight: 700, color: '#9CA3AF' }}>{items.length - openCount}</div>
          <div style={{ fontSize: 11, color: '#9CA3AF' }}>รายการว่าง</div>
        </div>
        <div style={{ flex: 1 }} />
        {isMyBranch && (
          <button onClick={autoSort} style={{ background: '#F9F5F0', border: '1px solid #D6C5B5', borderRadius: 8, padding: '6px 12px', fontSize: 13, cursor: 'pointer', color: '#4A2E1A' }}>
            ↕ จัดลำดับ
          </button>
        )}
      </div>

      {/* Item list */}
      <div style={{ padding: '12px 12px 80px' }}>
        {loading ? (
          <div style={{ textAlign: 'center', padding: 40, color: '#9CA3AF' }}>กำลังโหลด...</div>
        ) : items.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 40, color: '#9CA3AF' }}>
            <div style={{ fontSize: 40 }}>🍞</div>
            <div style={{ marginTop: 8 }}>ยังไม่มีรายการขนม</div>
          </div>
        ) : (
          items.map((item, idx) => {
            const qty = stockMap[item.id] || 0;
            const isSaving = saving === item.id;
            const canEdit = isMyBranch;
            return (
              <div
                key={item.id}
                data-drag-idx={idx}
                draggable={canEdit}
                onDragStart={() => onDragStart(idx)}
                onDragEnter={() => onDragEnter(idx)}
                onDragEnd={onDragEnd}
                onTouchStart={canEdit ? e => onTouchStart(e, idx) : undefined}
                onTouchMove={canEdit ? onTouchMove : undefined}
                onTouchEnd={canEdit ? e => onTouchEnd(e, idx) : undefined}
                style={{
                  background: '#fff',
                  borderRadius: 12,
                  marginBottom: 8,
                  padding: '12px 14px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: 12,
                  boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
                  opacity: item.is_open ? 1 : 0.55,
                  cursor: canEdit ? 'grab' : 'default',
                  userSelect: 'none',
                }}
              >
                {/* Drag handle */}
                {canEdit && <span style={{ color: '#D1C4B5', fontSize: 18, flexShrink: 0 }}>⠿</span>}

                {/* Icon */}
                <div style={{
                  width: 44, height: 44, borderRadius: 10, background: getBg(item.name),
                  display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 22, flexShrink: 0,
                }}>
                  {getIcon(item.name)}
                </div>

                {/* Name + open/close badge */}
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontWeight: 700, fontSize: 15, color: '#1F2937', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                    {item.name}
                  </div>
                  <div style={{ marginTop: 4 }}>
                    {canEdit ? (
                      <button
                        onClick={() => toggleOpen(item)}
                        style={{
                          fontSize: 11, padding: '2px 8px', borderRadius: 20, border: 'none', cursor: 'pointer', fontWeight: 600,
                          background: item.is_open ? '#DCFCE7' : '#F3F4F6',
                          color: item.is_open ? '#166534' : '#6B7280',
                        }}
                      >
                        {item.is_open ? '● เปิดขาย' : '○ ปิดขาย'}
                      </button>
                    ) : (
                      <span style={{ fontSize: 11, color: item.is_open ? '#16A34A' : '#9CA3AF' }}>
                        {item.is_open ? '● เปิดขาย' : '○ ปิดขาย'}
                      </span>
                    )}
                  </div>
                </div>

                {/* Qty stepper */}
                {canEdit ? (
                  <div style={{ display: 'flex', alignItems: 'center', gap: 0, background: '#F9F5F0', borderRadius: 10, padding: '2px' }}>
                    <button
                      onClick={() => adjustQty(item, -1)}
                      disabled={qty === 0 || isSaving}
                      style={{
                        width: 36, height: 36, border: 'none', background: qty === 0 ? 'transparent' : '#fff',
                        borderRadius: 8, fontSize: 20, cursor: qty === 0 ? 'not-allowed' : 'pointer',
                        color: qty === 0 ? '#D1D5DB' : '#DC2626', fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center',
                        boxShadow: qty === 0 ? 'none' : '0 1px 2px rgba(0,0,0,0.1)',
                      }}
                    >−</button>
                    <div style={{
                      width: 44, textAlign: 'center', fontWeight: 700, fontSize: 20,
                      color: qty > 0 ? '#166534' : '#9CA3AF',
                    }}>
                      {isSaving ? '…' : qty}
                    </div>
                    <button
                      onClick={() => adjustQty(item, +1)}
                      disabled={isSaving}
                      style={{
                        width: 36, height: 36, border: 'none', background: '#fff',
                        borderRadius: 8, fontSize: 20, cursor: 'pointer',
                        color: '#16A34A', fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center',
                        boxShadow: '0 1px 2px rgba(0,0,0,0.1)',
                      }}
                    >+</button>
                  </div>
                ) : (
                  <div style={{ fontWeight: 700, fontSize: 24, minWidth: 36, textAlign: 'right', color: qty > 0 ? '#166534' : '#9CA3AF' }}>
                    {qty || '—'}
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

      {/* Floating "Request add item" button — always visible */}
      <div style={{ position: 'fixed', bottom: 20, left: '50%', transform: 'translateX(-50%)', zIndex: 40 }}>
        <button
          onClick={() => setShowRequestAdd(true)}
          style={{
            background: '#4A2E1A', color: '#E8C89E', border: 'none', borderRadius: 24, padding: '13px 24px',
            fontSize: 15, fontWeight: 700, cursor: 'pointer', boxShadow: '0 4px 16px rgba(74,46,26,0.4)',
            display: 'flex', alignItems: 'center', gap: 8,
          }}
        >
          + ขอเพิ่มรายการ
        </button>
      </div>

      {/* Request Add Modal */}
      {showRequestAdd && (
        <ModalOverlay onClose={() => setShowRequestAdd(false)}>
          <div style={{ padding: '20px 20px 16px' }}>
            <div style={{ fontWeight: 700, fontSize: 17, marginBottom: 16 }}>ขอเพิ่มรายการขนม</div>
            <input
              autoFocus
              value={requestName}
              onChange={e => setRequestName(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && submitRequestAdd()}
              placeholder="ชื่อรายการขนม เช่น เลมอนทาร์ต"
              style={{
                width: '100%', padding: '12px 14px', borderRadius: 10, border: '1.5px solid #D6C5B5',
                fontSize: 16, boxSizing: 'border-box', fontFamily: 'inherit',
              }}
            />
            <div style={{ fontSize: 12, color: '#9CA3AF', marginTop: 8 }}>
              คำขอจะส่งให้แอดมินอนุมัติก่อนแสดงในระบบ
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 16 }}>
              <button onClick={() => setShowRequestAdd(false)} style={{ flex: 1, padding: 12, borderRadius: 10, border: '1.5px solid #E5E7EB', background: '#F9FAFB', cursor: 'pointer', fontSize: 15 }}>
                ยกเลิก
              </button>
              <button
                onClick={submitRequestAdd}
                disabled={!requestName.trim() || requestSending}
                style={{ flex: 2, padding: 12, borderRadius: 10, border: 'none', background: '#4A2E1A', color: '#E8C89E', cursor: 'pointer', fontSize: 15, fontWeight: 700, opacity: requestName.trim() ? 1 : 0.5 }}
              >
                {requestSending ? 'กำลังส่ง...' : 'ส่งคำขอ'}
              </button>
            </div>
          </div>
        </ModalOverlay>
      )}

      {/* History Modal */}
      {showHistory && (
        <ModalOverlay onClose={() => setShowHistory(false)}>
          <div style={{ padding: '16px 16px 8px', borderBottom: '1px solid #F3F4F6', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <span style={{ fontWeight: 700, fontSize: 16 }}>📋 ประวัติ 30 วัน</span>
            <button onClick={() => setShowHistory(false)} style={{ background: 'none', border: 'none', fontSize: 22, cursor: 'pointer', color: '#6B7280' }}>✕</button>
          </div>
          <div style={{ overflowY: 'auto', maxHeight: '65vh', padding: '8px 0' }}>
            {logsLoading ? (
              <div style={{ textAlign: 'center', padding: 32, color: '#9CA3AF' }}>กำลังโหลด...</div>
            ) : logs.length === 0 ? (
              <div style={{ textAlign: 'center', padding: 32, color: '#9CA3AF' }}>ยังไม่มีประวัติ</div>
            ) : (
              logs.map(log => (
                <div key={log.id} style={{ padding: '10px 16px', borderBottom: '1px solid #F9F5F0', display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                  <div style={{ fontSize: 18, flexShrink: 0 }}>{getIcon(log.item_name)}</div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontSize: 14, fontWeight: 600, color: '#1F2937' }}>{log.item_name}</div>
                    <div style={{ fontSize: 13, color: '#6B7280' }}>
                      {ACTION_LABELS[log.action] || log.action}
                      {log.action === 'adjust' && log.delta != null && (
                        <span style={{ marginLeft: 6, color: log.delta > 0 ? '#16A34A' : '#DC2626', fontWeight: 700 }}>
                          {log.delta > 0 ? `+${log.delta}` : log.delta} → {log.qty_after} ชิ้น
                        </span>
                      )}
                    </div>
                    <div style={{ fontSize: 11, color: '#9CA3AF', marginTop: 2 }}>
                      {log.emp_name} · {fmtTime(log.created_at)}
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </ModalOverlay>
      )}
    </div>
  );
}

// ─── ModalOverlay ─────────────────────────────────────────────────────────────
function ModalOverlay({ children, onClose }) {
  return (
    <div
      onClick={onClose}
      style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', zIndex: 100, display: 'flex', alignItems: 'flex-end', justifyContent: 'center' }}
    >
      <div
        onClick={e => e.stopPropagation()}
        style={{ background: '#fff', borderRadius: '20px 20px 0 0', width: '100%', maxWidth: 520, animation: 'slideUp 0.2s ease' }}
      >
        {children}
      </div>
      <style>{`@keyframes slideUp { from { transform: translateY(100%) } to { transform: translateY(0) } }`}</style>
    </div>
  );
}
