import { useEffect, useState, useRef, useCallback } from 'react';
import { supabase } from '../../lib/supabase';
import { useAuthStore } from '../../store/authStore';

// ─── Icon mapping ─────────────────────────────────────────────────────────────
const ICON_MAP = [
  [/ชีสเค้ก|cheese\s*cake/i,        '🍰', '#FEF9C3'],
  [/ช็อค|chocolate|โกโก้/i,         '🍫', '#FEF3C7'],
  [/มัฟฟิน|muffin/i,                '🧁', '#FCE7F3'],
  [/คุกกี้|cookie/i,                '🍪', '#FFF7ED'],
  [/ครัวซอง|croissant/i,            '🥐', '#FEF3C7'],
  [/ทาร์ต|tart/i,                   '🥧', '#FEF9C3'],
  [/มาการอง|macaron/i,              '💜', '#EDE9FE'],
  [/บราวนี่|brownie/i,              '🟫', '#FEF3C7'],
  [/วาฟเฟิล|waffle/i,               '🧇', '#FEF9C3'],
  [/ขนมปัง|bread|บาแก็ต/i,         '🥖', '#FEF9C3'],
  [/มาชา|matcha/i,                  '🍵', '#ECFDF5'],
  [/สตรอว์|strawberry/i,            '🍓', '#FFF0F0'],
  [/เลมอน|lemon/i,                  '🍋', '#FEFCE8'],
  [/พาย|pie/i,                      '🥧', '#FEF9C3'],
  [/โรล|roll|ม้วน/i,                '🌀', '#F0F9FF'],
  [/เค้ก|cake/i,                    '🎂', '#FCE7F3'],
];

function getIcon(name) {
  for (const [re, icon] of ICON_MAP) if (re.test(name)) return icon;
  return '🍞';
}
function getBg(name) {
  for (const [re, , bg] of ICON_MAP) if (re.test(name)) return bg;
  return '#F9FAFB';
}

// ─── Canvas Export ────────────────────────────────────────────────────────────
function drawExport(canvas, { items, stockMap, spoiledMap, branchName, empName }) {
  const W = 800;
  const LINE_H = 46;
  const HEADER_H = 160;
  const FOOTER_H = 72;
  const H = HEADER_H + LINE_H + items.length * LINE_H + FOOTER_H;
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d');
  const F = (size, bold) => `${bold ? 'bold ' : ''}${size}px "Sarabun","Tahoma","Arial",sans-serif`;

  ctx.fillStyle = '#FFFFFF';
  ctx.fillRect(0, 0, W, H);

  // Header strip
  ctx.fillStyle = '#4A2E1A';
  ctx.fillRect(0, 0, W, 100);

  ctx.fillStyle = '#E8C89E';
  ctx.font = F(28, true);
  ctx.textAlign = 'center';
  ctx.fillText('☕ JE BAR Coffee & Pastry', W / 2, 38);
  ctx.fillStyle = '#FFFFFF';
  ctx.font = F(20, true);
  ctx.fillText('ใบเช็คสต็อคขนม', W / 2, 68);
  ctx.font = F(14);
  const dateStr = new Date().toLocaleDateString('th-TH', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' });
  ctx.fillText(`${dateStr}  |  สาขา: ${branchName}  |  ผู้เช็ค: ${empName}`, W / 2, 92);

  // Sub-header bar
  ctx.fillStyle = '#F9F5F0';
  ctx.fillRect(0, 100, W, 60);
  ctx.fillStyle = '#6B4226';
  ctx.font = F(13);
  ctx.textAlign = 'left';
  const hasStockCount = items.filter(i => (stockMap[i.id] || 0) > 0).length;
  const totalSpoiled = items.reduce((s, i) => s + (spoiledMap[i.id] || 0), 0);
  ctx.fillText(`รายการทั้งหมด: ${items.length}  |  มีสินค้า: ${hasStockCount}  |  ขนมเสีย: ${totalSpoiled} ชิ้น`, 32, 136);

  // Table header
  const y0 = HEADER_H;
  ctx.fillStyle = '#4A2E1A';
  ctx.fillRect(0, y0, W, LINE_H);
  ctx.fillStyle = '#FFFFFF';
  ctx.font = F(14, true);
  ctx.textAlign = 'left';
  ctx.fillText('#', 24, y0 + 30);
  ctx.fillText('รายการขนม', 68, y0 + 30);
  ctx.textAlign = 'right';
  ctx.fillText('เสีย', W - 170, y0 + 30);
  ctx.fillText('จำนวน (ชิ้น)', W - 32, y0 + 30);

  // Rows
  items.forEach((item, idx) => {
    const ry = y0 + LINE_H + idx * LINE_H;
    const qty = stockMap[item.id] || 0;
    const spoiled = spoiledMap[item.id] || 0;
    ctx.fillStyle = idx % 2 === 0 ? '#FFFFFF' : '#FAF7F3';
    ctx.fillRect(0, ry, W, LINE_H);

    // Divider
    ctx.strokeStyle = '#E5DDD5';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(0, ry + LINE_H - 0.5);
    ctx.lineTo(W, ry + LINE_H - 0.5);
    ctx.stroke();

    // Row number
    ctx.fillStyle = '#9CA3AF';
    ctx.font = F(13);
    ctx.textAlign = 'left';
    ctx.fillText(String(idx + 1), 24, ry + 30);

    // Item name
    ctx.fillStyle = '#1F2937';
    ctx.font = F(15, true);
    ctx.fillText(`${getIcon(item.name)}  ${item.name}`, 68, ry + 30);

    // Spoiled
    ctx.textAlign = 'right';
    ctx.fillStyle = spoiled > 0 ? '#DC2626' : '#D1D5DB';
    ctx.font = F(14, spoiled > 0);
    ctx.fillText(spoiled > 0 ? String(spoiled) : '—', W - 170, ry + 30);

    // Qty
    if (qty > 0) {
      ctx.fillStyle = '#166534';
      ctx.font = F(18, true);
    } else {
      ctx.fillStyle = '#9CA3AF';
      ctx.font = F(15);
    }
    ctx.fillText(qty > 0 ? String(qty) : '—', W - 32, ry + 30);
  });

  // Footer
  const fy = y0 + LINE_H + items.length * LINE_H;
  ctx.fillStyle = '#4A2E1A';
  ctx.fillRect(0, fy, W, FOOTER_H);
  ctx.fillStyle = '#E8C89E';
  ctx.font = F(13, true);
  ctx.textAlign = 'center';
  const totalQty = items.reduce((s, i) => s + (stockMap[i.id] || 0), 0);
  ctx.fillText(`รวม ${totalQty} ชิ้น  |  เสีย ${totalSpoiled} ชิ้น  |  Generated by LUCID HR · JE BAR`, W / 2, fy + 42);
}

async function exportToImage({ items, stockMap, spoiledMap, branchName, empName }) {
  const canvas = document.createElement('canvas');
  drawExport(canvas, { items, stockMap, spoiledMap, branchName, empName });
  return new Promise(resolve => canvas.toBlob(resolve, 'image/png'));
}

// ─── Spoiled reasons ──────────────────────────────────────────────────────────
const SPOILED_REASONS = [
  { value: 'expired',  label: '🗓 หมดอายุ' },
  { value: 'damaged',  label: '💥 เสียหาย/แตก' },
  { value: 'quality',  label: '❌ คุณภาพไม่ผ่าน' },
  { value: 'other',    label: '📝 อื่นๆ' },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
function fmtTime(ts) {
  const d = new Date(ts);
  return d.toLocaleString('th-TH', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

const ACTION_LABELS = {
  adjust: 'ปรับจำนวน',
  spoiled: 'บันทึกขนมเสีย',
  open: 'เปิดขาย',
  close: 'ปิดขาย',
  request_add: 'ขอเพิ่มรายการ',
  request_delete: 'ขอลบรายการ',
  approve: 'อนุมัติ',
  reject: 'ปฏิเสธ',
  reorder: 'เรียงลำดับ',
};

// ─── Main Component ───────────────────────────────────────────────────────────
export default function CakeStockPage({ navigate }) {
  const { employee } = useAuthStore();
  const myBranchId = employee?.branch_id;
  const empId = employee?.id;
  const empName = employee?.nickname || employee?.name || 'พนักงาน';
  const orgId = employee?.org_id;

  const [branches, setBranches] = useState([]);
  const [activeBranchId, setActiveBranchId] = useState(myBranchId || null);
  const [items, setItems] = useState([]);         // cake_items (active)
  const [stockMap, setStockMap] = useState({});   // { item_id: qty }
  const [spoiledMap, setSpoiledMap] = useState({}); // { item_id: qty_spoiled }
  const [spoiledDetails, setSpoiledDetails] = useState({}); // { item_id: { reason, photo } }
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(null);
  const [operateSyncing, setOperateSyncing] = useState(false);
  const [operateSyncMsg, setOperateSyncMsg] = useState('');
  const [savingSpoiled, setSavingSpoiled] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [lastSubmitted, setLastSubmitted] = useState(null); // ISO string

  // Modals
  const [showHistory, setShowHistory] = useState(false);
  const [logs, setLogs] = useState([]);
  const [logsLoading, setLogsLoading] = useState(false);
  const [showRequestAdd, setShowRequestAdd] = useState(false);
  const [requestName, setRequestName] = useState('');
  const [requestSending, setRequestSending] = useState(false);
  const [pendingDelete, setPendingDelete] = useState(null); // item to request delete

  // Drag-to-reorder
  const dragItem = useRef(null);
  const dragOver = useRef(null);
  const [dragActiveIdx, setDragActiveIdx] = useState(null);   // which item is being dragged
  const [dragOverIdx, setDragOverIdx] = useState(null);       // which slot it's hovering

  // Menu suggestions for the "request add" modal
  const [menuSuggestions, setMenuSuggestions] = useState([]);

  // Non-beverage categories to exclude from sync (case-insensitive)
  const BEVERAGE_CATS = ['beverage', 'drink', 'coffee', 'tea', 'เครื่องดื่ม', 'กาแฟ', 'ชา'];
  function isNonBeverage(m) {
    const cat = (m.category || '').toLowerCase();
    return !BEVERAGE_CATS.some(c => cat.includes(c));
  }

  // Auto-sync ALL non-beverage menu items (รวม หยุดขาย) from jebar_app_state → cake_items
  useEffect(() => {
    if (!orgId) return;
    supabase.from('jebar_app_state')
      .select('db')
      .eq('shop_code', 'jebar')
      .limit(1)
      .single()
      .then(async ({ data, error }) => {
        if (error || !data?.db?.menus) return;
        const menus = data.db.menus;
        // รวมทุก non-beverage ไม่กรอง status
        const bakeryMenus = menus.filter(m => isNonBeverage(m));

        // Modal suggestions = เฉพาะที่ยังขายอยู่
        setMenuSuggestions(bakeryMenus.filter(m => m.status !== 'หยุดขาย').map(m => m.name));

        if (!bakeryMenus.length) return;
        const { data: existing } = await supabase
          .from('cake_items').select('name').eq('org_id', orgId);
        const existingNames = new Set((existing || []).map(e => e.name));
        const toInsert = bakeryMenus
          .filter(m => !existingNames.has(m.name))
          .map((m, i) => ({
            org_id: orgId,
            name: m.name,
            sort_order: 9000 + i,
            is_open: m.status !== 'หยุดขาย',
          }));
        if (toInsert.length) {
          await supabase.from('cake_items').insert(toInsert);
          load();
        }
      });
  }, [orgId]);

  // Load branches
  useEffect(() => {
    if (!orgId) return;
    supabase.from('branches').select('id,label').eq('org_id', orgId).order('label')
      .then(({ data }) => {
        if (data) setBranches(data);
      });
  }, [orgId]);

  // Set default tab to own branch once branches loaded
  useEffect(() => {
    if (branches.length && !activeBranchId) {
      setActiveBranchId(myBranchId || branches[0]?.id);
    }
  }, [branches, myBranchId, activeBranchId]);

  // Load items + stock for active branch (or all branches)
  const load = useCallback(async () => {
    if (!orgId) return;
    setLoading(true);
    try {
      let stockPromise;
      if (activeBranchId === 'all') {
        stockPromise = supabase.from('cake_stock').select('item_id,qty,qty_spoiled').eq('org_id', orgId);
      } else if (activeBranchId) {
        stockPromise = supabase.from('cake_stock').select('item_id,qty,qty_spoiled').eq('org_id', orgId).eq('branch_id', activeBranchId);
      } else {
        stockPromise = Promise.resolve({ data: [] });
      }
      const [{ data: itemData }, { data: stockData }] = await Promise.all([
        supabase.from('cake_items')
          .select('id,name,sort_order,is_open,status')
          .eq('org_id', orgId)
          .in('status', ['active'])
          .order('sort_order'),
        stockPromise,
      ]);
      if (itemData) setItems(itemData);
      if (stockData) {
        const m = {};
        const s = {};
        stockData.forEach(r => {
          m[r.item_id] = (m[r.item_id] || 0) + r.qty;
          s[r.item_id] = (s[r.item_id] || 0) + (r.qty_spoiled || 0);
        });
        setStockMap(m);
        setSpoiledMap(s);
      }
    } finally {
      setLoading(false);
    }
  }, [orgId, activeBranchId]);

  useEffect(() => { load(); }, [load]);

  // isMyBranch: false in 'all' mode (read-only), true on own branch or if no branch assigned
  const isMyBranch = activeBranchId !== 'all' && (!myBranchId || activeBranchId === myBranchId);

  // Write a log event
  async function writeLog(itemId, itemName, action, delta, qtyAfter, note) {
    await supabase.from('cake_stock_log').insert({
      org_id: orgId,
      branch_id: activeBranchId,
      item_id: itemId,
      item_name: itemName,
      emp_id: empId,
      emp_name: empName,
      action,
      delta,
      qty_after: qtyAfter,
      note,
    });
  }

  // Adjust qty (upsert into cake_stock)
  async function adjustQty(item, delta) {
    if (!isMyBranch) return;
    const prev = stockMap[item.id] || 0;
    const next = Math.max(0, prev + delta);
    setSaving(item.id);
    setStockMap(old => ({ ...old, [item.id]: next }));
    try {
      const { error } = await supabase.from('cake_stock').upsert({
        org_id: orgId,
        branch_id: activeBranchId,
        item_id: item.id,
        qty: next,
        updated_by: empId,
        updated_at: new Date().toISOString(),
      }, { onConflict: 'branch_id,item_id' });
      if (error) throw error;
      await writeLog(item.id, item.name, 'adjust', delta, next, null);
    } catch (err) {
      setStockMap(old => ({ ...old, [item.id]: prev }));
      alert('บันทึกไม่สำเร็จ: ' + (err?.message || 'กรุณาลองใหม่'));
    } finally {
      setSaving(null);
    }
  }

  // Adjust spoiled qty
  async function adjustSpoiled(item, delta) {
    if (!isMyBranch) return;
    const prev = spoiledMap[item.id] || 0;
    const next = Math.max(0, prev + delta);
    setSavingSpoiled(item.id);
    setSpoiledMap(old => ({ ...old, [item.id]: next }));
    try {
      const { error } = await supabase.from('cake_stock').upsert({
        org_id: orgId,
        branch_id: activeBranchId,
        item_id: item.id,
        qty_spoiled: next,
        updated_by: empId,
        updated_at: new Date().toISOString(),
      }, { onConflict: 'branch_id,item_id' });
      if (error) throw error;
      await writeLog(item.id, item.name, 'spoiled', delta, next, null);
    } catch (err) {
      setSpoiledMap(old => ({ ...old, [item.id]: prev }));
      alert('บันทึกไม่สำเร็จ: ' + (err?.message || 'กรุณาลองใหม่'));
    } finally {
      setSavingSpoiled(null);
    }
  }

  // Toggle open/close (is_open) — only own branch context, but is_open is global per item
  // Only admin can do this; employees see toggle but request goes through
  // For simplicity: update is_open directly (admin-like), per approved design
  async function toggleOpen(item) {
    const newOpen = !item.is_open;
    setItems(prev => prev.map(i => i.id === item.id ? { ...i, is_open: newOpen } : i));
    await supabase.from('cake_items').update({ is_open: newOpen, updated_at: new Date().toISOString() }).eq('id', item.id);
    await writeLog(item.id, item.name, newOpen ? 'open' : 'close', null, null, null);
  }

  // Auto-sort: open items first
  async function autoSort() {
    const sorted = [
      ...items.filter(i => i.is_open),
      ...items.filter(i => !i.is_open),
    ].map((item, idx) => ({ ...item, sort_order: idx }));
    setItems(sorted);
    await Promise.all(
      sorted.map(item => supabase.from('cake_items').update({ sort_order: item.sort_order }).eq('id', item.id))
    );
    await writeLog(null, 'ทั้งหมด', 'reorder', null, null, 'auto-sort');
  }

  // Drag handlers
  function onDragStart(idx) { dragItem.current = idx; setDragActiveIdx(idx); setDragOverIdx(idx); }
  function onDragEnter(idx) { dragOver.current = idx; setDragOverIdx(idx); }
  function onDragEnd() {
    setDragActiveIdx(null);
    setDragOverIdx(null);
    if (dragItem.current === null || dragOver.current === null) return;
    const newItems = [...items];
    const [moved] = newItems.splice(dragItem.current, 1);
    newItems.splice(dragOver.current, 0, moved);
    dragItem.current = null;
    dragOver.current = null;
    const updated = newItems.map((item, idx) => ({ ...item, sort_order: idx }));
    setItems(updated);
    Promise.all(
      updated.map(item => supabase.from('cake_items').update({ sort_order: item.sort_order }).eq('id', item.id))
    ).then(() => writeLog(null, 'ทั้งหมด', 'reorder', null, null, 'drag'));
  }

  // Move item up or down (mobile-friendly alternative to drag)
  function moveItem(idx, dir) {
    const newIdx = idx + dir;
    if (newIdx < 0 || newIdx >= items.length) return;
    const newItems = [...items];
    [newItems[idx], newItems[newIdx]] = [newItems[newIdx], newItems[idx]];
    const updated = newItems.map((item, i) => ({ ...item, sort_order: i }));
    setItems(updated);
    Promise.all(
      updated.map(item => supabase.from('cake_items').update({ sort_order: item.sort_order }).eq('id', item.id))
    ).then(() => writeLog(null, 'ทั้งหมด', 'reorder', null, null, 'move'));
  }

  // Touch drag state
  const touchDragIdx = useRef(null);

  function onTouchStart(e, idx) {
    touchDragIdx.current = idx;
    e.currentTarget.style.opacity = '0.5';
  }
  function onTouchMove(e) {
    e.preventDefault();
    const touch = e.touches[0];
    const el = document.elementFromPoint(touch.clientX, touch.clientY);
    const row = el?.closest('[data-drag-idx]');
    if (row) dragOver.current = parseInt(row.dataset.dragIdx);
  }
  function onTouchEnd(e, idx) {
    e.currentTarget.style.opacity = '1';
    dragItem.current = touchDragIdx.current;
    onDragEnd();
    touchDragIdx.current = null;
  }

  // Request to add item
  async function submitRequestAdd() {
    if (!requestName.trim()) return;
    setRequestSending(true);
    try {
      await supabase.from('cake_items').insert({
        org_id: orgId,
        name: requestName.trim(),
        sort_order: 9999,
        is_open: true,
        status: 'pending_add',
        requested_by: empId,
      });
      await writeLog(null, requestName.trim(), 'request_add', null, null, `ขอเพิ่มโดย ${empName}`);
      setShowRequestAdd(false);
      setRequestName('');
      alert('ส่งคำขอแล้ว รอแอดมินอนุมัติ');
    } finally {
      setRequestSending(false);
    }
  }

  // Request to delete item
  async function submitRequestDelete(item) {
    await supabase.from('cake_items').update({ status: 'pending_delete', requested_by: empId }).eq('id', item.id);
    await writeLog(item.id, item.name, 'request_delete', null, null, `ขอลบโดย ${empName}`);
    setPendingDelete(null);
    alert(`ส่งคำขอลบ "${item.name}" แล้ว รอแอดมินอนุมัติ`);
    load();
  }

  // ดึงยอดจาก Operate (jebar_app_state → shopStock)
  async function syncFromOperate() {
    if (!isMyBranch || operateSyncing) return;
    setOperateSyncing(true);
    setOperateSyncMsg('');
    try {
      const { data, error } = await supabase
        .from('jebar_app_state')
        .select('db')
        .eq('shop_code', 'jebar')
        .limit(1)
        .single();
      if (error || !data?.db) { setOperateSyncMsg('ดึงข้อมูล Operate ไม่สำเร็จ'); return; }

      const menus = data.db.menus || [];
      const shopStock = data.db.shopStock || [];

      // หา label ของ branch ที่ active อยู่
      const activeBranch = branches.find(b => b.id === activeBranchId);
      const branchLabel = activeBranch?.label || '';

      // normalize สำหรับ fuzzy match
      const norm = s => (s || '').trim().toLowerCase().replace(/\s+/g, '');

      // map menuId → onHand โดยกรอง branchId ตรงกับ branchLabel
      const onHandByMenuId = {};
      shopStock.forEach(s => {
        if (norm(s.branchId) === norm(branchLabel) || !branchLabel) {
          onHandByMenuId[s.menuId] = Number(s.onHand) || 0;
        }
      });

      // map ชื่อ (normalized) → onHand
      const onHandByName = {};
      menus.forEach(m => {
        if (onHandByMenuId[m.id] !== undefined) {
          onHandByName[norm(m.name)] = onHandByMenuId[m.id];
        }
      });

      // อัปเดต cake_stock และ stockMap
      let updated = 0;
      const newStockMap = { ...stockMap };
      for (const item of items) {
        const key = norm(item.name);
        if (onHandByName[key] === undefined) continue;
        const newQty = onHandByName[key];
        const { error: upsertErr } = await supabase.from('cake_stock').upsert({
          org_id: orgId,
          branch_id: activeBranchId,
          item_id: item.id,
          qty: newQty,
          updated_by: empId,
          updated_at: new Date().toISOString(),
        }, { onConflict: 'branch_id,item_id' });
        if (!upsertErr) {
          newStockMap[item.id] = newQty;
          updated++;
        }
      }
      setStockMap(newStockMap);
      setOperateSyncMsg(updated > 0 ? `ดึงยอดจาก Operate แล้ว ${updated} รายการ` : 'ไม่พบข้อมูลสต็อกจาก Operate');
    } catch {
      setOperateSyncMsg('เกิดข้อผิดพลาด ลองใหม่อีกครั้ง');
    } finally {
      setOperateSyncing(false);
      setTimeout(() => setOperateSyncMsg(''), 4000);
    }
  }

  // Load history log
  async function openHistory() {
    setShowHistory(true);
    setLogsLoading(true);
    const cutoff = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
    const { data } = await supabase.from('cake_stock_log')
      .select('*')
      .eq('org_id', orgId)
      .eq('branch_id', activeBranchId)
      .gte('created_at', cutoff)
      .order('created_at', { ascending: false })
      .limit(200);
    setLogs(data || []);
    setLogsLoading(false);
  }

  // Export image
  async function handleExport() {
    const activeBranch = branches.find(b => b.id === activeBranchId);
    const branchName = activeBranchId === 'all' ? 'รวมทุกสาขา' : (activeBranch?.label || 'ไม่ระบุสาขา');
    const blob = await exportToImage({ items: items.filter(i => i.is_open), stockMap, spoiledMap, branchName, empName });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cake-stock-${branchName}-${new Date().toISOString().slice(0, 10)}.png`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const totalQty = items.reduce((s, i) => s + (stockMap[i.id] || 0), 0);
  const openCount = items.filter(i => (stockMap[i.id] || 0) > 0).length;

  // Submit report snapshot to employee_ops_entries (task_key='cake-stock')
  async function submitReport() {
    if (!isMyBranch || submitting) return;
    const activeBranch = branches.find(b => b.id === activeBranchId);
    const branchName = activeBranch?.label || 'ไม่ระบุสาขา';
    // Upload spoiled photos to Storage, replace base64 with URLs
    const photoUrls = {};
    const spoiledItemsWithPhoto = items.filter(i => i.is_open && spoiledDetails[i.id]?.photo?.startsWith('data:'));
    for (const item of spoiledItemsWithPhoto) {
      try {
        const b64 = spoiledDetails[item.id].photo;
        const [meta, data] = b64.split(',');
        const mime = (meta.match(/:(.*?);/) || [])[1] || 'image/jpeg';
        const bytes = atob(data);
        const arr = new Uint8Array(bytes.length);
        for (let k = 0; k < bytes.length; k++) arr[k] = bytes.charCodeAt(k);
        const blob = new Blob([arr], { type: mime });
        const ext = mime.split('/')[1] || 'jpg';
        const path = `waste/${orgId}/${activeBranchId}/${Date.now()}-${item.id}.${ext}`;
        const { data: up, error: upErr } = await supabase.storage.from('jebar-images').upload(path, blob, { contentType: mime, upsert: true });
        if (!upErr && up) {
          const { data: pub } = supabase.storage.from('jebar-images').getPublicUrl(up.path);
          photoUrls[item.id] = pub?.publicUrl || '';
        }
      } catch { /* ถ้า upload ไม่สำเร็จ ข้ามไป */ }
    }

    const openItems = items.filter(i => i.is_open).map(i => ({
      name: i.name,
      qty: stockMap[i.id] || 0,
      qty_spoiled: spoiledMap[i.id] || 0,
      spoiled_reason: (spoiledDetails[i.id]?.reason) || '',
      spoiled_note: (spoiledDetails[i.id]?.note) || '',
      spoiled_photo: photoUrls[i.id] || '',
    }));

    // Check if someone from same branch already submitted today
    const todayStart = new Date(); todayStart.setHours(0, 0, 0, 0);
    const { data: existing } = await supabase
      .from('employee_ops_entries')
      .select('payload,created_at')
      .eq('task_key', 'cake-stock')
      .eq('org_id', orgId)
      .gte('created_at', todayStart.toISOString())
      .order('created_at', { ascending: false })
      .limit(10);

    // Filter to same branch only (payload.branch_id)
    const sameBranch = (existing || []).filter(r => r.payload?.branch_id === activeBranchId);
    if (sameBranch.length > 0) {
      const prev = sameBranch[0];
      const prevName = prev.payload?.submitted_by || 'ไม่ระบุ';
      const prevTime = new Date(prev.created_at).toLocaleTimeString('th-TH', { hour: '2-digit', minute: '2-digit' });
      const isSelf = prevName === empName;
      const msg = isSelf
        ? `คุณส่งรายงานไปแล้วเมื่อ ${prevTime}\nต้องการส่งอัปเดตข้อมูลใหม่ไหม?`
        : `${prevName} ส่งรายงานสาขานี้แล้วเมื่อ ${prevTime}\nต้องการส่งเพิ่มเติมไหม?`;
      if (!window.confirm(msg)) return;
    }

    setSubmitting(true);
    try {
      const { error } = await supabase.rpc('employee_submit_ops_entry', {
        p_emp_id: empId,
        p_task_key: 'cake-stock',
        p_payload: {
          submitted_by: empName,
          branch_id: activeBranchId,
          branch_name: branchName,
          submitted_at: new Date().toISOString(),
          items: openItems,
          total_qty: openItems.reduce((s, i) => s + i.qty, 0),
          total_spoiled: openItems.reduce((s, i) => s + i.qty_spoiled, 0),
        },
      });
      if (error) throw error;
      const now = new Date().toISOString();
      setLastSubmitted(now);
      alert(`ส่งรายงานแล้ว ✓\n${branchName} · ${openItems.length} รายการ\n${new Date(now).toLocaleTimeString('th-TH', { hour: '2-digit', minute: '2-digit' })}`);
    } catch (err) {
      alert('ส่งรายงานไม่สำเร็จ: ' + (err?.message || 'กรุณาลองใหม่'));
    } finally {
      setSubmitting(false);
    }
  }

  // ─── Render ────────────────────────────────────────────────────────────────
  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)' }}>
      {/* Top bar */}
      <div style={{ background: 'var(--ink)', color: '#fff', padding: '14px 16px', display: 'flex', alignItems: 'center', gap: 10, position: 'sticky', top: 0, zIndex: 50 }}>
        <button onClick={() => navigate('/emp/ops')} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,.7)', fontSize: 22, cursor: 'pointer', padding: '0 4px' }}>←</button>
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 700, fontSize: 17 }}>สต็อกขนม</div>
          <div style={{ fontSize: 12, opacity: 0.65 }}>{isMyBranch ? 'สาขาของคุณ — แก้ไขได้' : 'ดูข้อมูลเท่านั้น'}</div>
        </div>
        <button onClick={openHistory} style={{ background: 'rgba(255,255,255,0.12)', border: '1px solid rgba(255,255,255,.2)', color: '#fff', borderRadius: 8, padding: '6px 12px', fontSize: 13, cursor: 'pointer' }}>ประวัติ</button>
        <button onClick={handleExport} style={{ background: 'rgba(255,255,255,0.12)', border: '1px solid rgba(255,255,255,.2)', color: '#fff', borderRadius: 8, padding: '6px 12px', fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>Export</button>
      </div>

      {/* Operate sync message */}
      {operateSyncMsg && (
        <div style={{ background: 'var(--accent-soft)', borderBottom: '1px solid var(--line)', padding: '8px 16px', fontSize: 13, color: 'var(--accent)', display: 'flex', alignItems: 'center', gap: 8 }}>
          {operateSyncMsg}
        </div>
      )}

      {/* Branch tabs */}
      {branches.length > 0 && (
        <div style={{ background: 'var(--surface)', borderBottom: '1px solid var(--line)', overflowX: 'auto', display: 'flex', padding: '0 8px' }}>
          {/* All-branches tab */}
          <button
            onClick={() => setActiveBranchId('all')}
            style={{
              whiteSpace: 'nowrap', padding: '12px 16px', border: 'none', cursor: 'pointer', fontSize: 14,
              fontWeight: activeBranchId === 'all' ? 700 : 400,
              color: activeBranchId === 'all' ? 'var(--ink)' : 'var(--muted)',
              background: 'none',
              borderBottom: activeBranchId === 'all' ? '2px solid var(--accent)' : '2px solid transparent',
            }}
          >
            รวมทุกสาขา
          </button>
          {branches.map(b => (
            <button
              key={b.id}
              onClick={() => setActiveBranchId(b.id)}
              style={{
                whiteSpace: 'nowrap', padding: '12px 16px', border: 'none', cursor: 'pointer', fontSize: 14,
                fontWeight: b.id === activeBranchId ? 700 : 400,
                color: b.id === activeBranchId ? 'var(--ink)' : 'var(--muted)',
                background: 'none',
                borderBottom: b.id === activeBranchId ? '2px solid var(--accent)' : '2px solid transparent',
              }}
            >
              {b.id === myBranchId ? '★ ' : ''}{b.label}
            </button>
          ))}
        </div>
      )}

      {/* Summary bar */}
      <div style={{ background: 'var(--surface)', padding: '12px 16px', display: 'flex', gap: 16, borderBottom: '1px solid var(--line)' }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 22, fontWeight: 700, color: 'var(--ink)' }}>{totalQty}</div>
          <div style={{ fontSize: 11, color: 'var(--muted)' }}>รวมทั้งหมด</div>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 22, fontWeight: 700, color: 'var(--accent)' }}>{openCount}</div>
          <div style={{ fontSize: 11, color: 'var(--muted)' }}>รายการมีสินค้า</div>
        </div>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 22, fontWeight: 700, color: 'var(--muted)' }}>{items.length - openCount}</div>
          <div style={{ fontSize: 11, color: 'var(--muted)' }}>รายการว่าง</div>
        </div>
        <div style={{ flex: 1 }} />
        {isMyBranch && (
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <button onClick={syncFromOperate} disabled={operateSyncing}
              style={{ background: 'var(--accent-soft)', border: '1px solid var(--accent)', borderRadius: 8, padding: '6px 12px', fontSize: 13, cursor: 'pointer', color: 'var(--accent)', opacity: operateSyncing ? 0.6 : 1 }}>
              {operateSyncing ? '...' : '↻'} Operate
            </button>
            <button onClick={autoSort} style={{ background: 'var(--bg)', border: '1px solid var(--line)', borderRadius: 8, padding: '6px 12px', fontSize: 13, cursor: 'pointer', color: 'var(--ink)' }}>
              ↕ จัดลำดับ
            </button>
            <button onClick={() => setShowRequestAdd(true)} style={{ background: 'var(--ink)', border: 'none', borderRadius: 8, padding: '6px 12px', fontSize: 13, fontWeight: 700, cursor: 'pointer', color: '#fff' }}>
              + เพิ่ม
            </button>
          </div>
        )}
      </div>

      {/* Submit report bar — only own branch */}
      {isMyBranch && (
        <div style={{ background: lastSubmitted ? 'var(--accent-soft)' : 'var(--bg)', padding: '10px 16px', borderBottom: '1px solid var(--line)', display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{ flex: 1 }}>
            {lastSubmitted ? (
              <div style={{ fontSize: 13, color: 'var(--accent)', fontWeight: 600 }}>
                ✓ ส่งรายงานแล้ว · {new Date(lastSubmitted).toLocaleTimeString('th-TH', { hour: '2-digit', minute: '2-digit' })}
              </div>
            ) : (
              <div style={{ fontSize: 13, color: 'var(--muted)' }}>
                เช็คสต็อคเสร็จแล้ว? กดส่งให้แอดมิน
              </div>
            )}
          </div>
          <button
            onClick={submitReport}
            disabled={submitting}
            style={{
              background: lastSubmitted ? 'var(--accent)' : 'var(--ink)',
              color: '#fff', border: 'none', borderRadius: 10,
              padding: '10px 20px', fontSize: 14, fontWeight: 700,
              cursor: submitting ? 'not-allowed' : 'pointer',
              opacity: submitting ? 0.7 : 1,
            }}
          >
            {submitting ? 'กำลังส่ง...' : lastSubmitted ? '✓ ส่งอีกครั้ง' : 'ส่งรายงาน'}
          </button>
        </div>
      )}

      {/* Item list */}
      <div style={{ padding: '12px 12px 24px' }}>
        {loading ? (
          <div style={{ textAlign: 'center', padding: 40, color: 'var(--muted)' }}>กำลังโหลด...</div>
        ) : items.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 40, color: 'var(--muted)' }}>
            <div style={{ fontSize: 40 }}>🍞</div>
            <div style={{ marginTop: 8 }}>ยังไม่มีรายการขนม</div>
          </div>
        ) : (
          items.map((item, idx) => {
            const qty = stockMap[item.id] || 0;
            const spoiled = spoiledMap[item.id] || 0;
            const isSaving = saving === item.id;
            const isSavingSpoiled = savingSpoiled === item.id;
            const canEdit = isMyBranch;
            const details = spoiledDetails[item.id] || {};
            const photoInputId = `spoiled-photo-${item.id}`;
            return (
              <div key={item.id} style={{ marginBottom: 8 }}>
              <div
                data-drag-idx={idx}
                draggable={canEdit}
                onDragStart={() => onDragStart(idx)}
                onDragEnter={() => onDragEnter(idx)}
                onDragOver={canEdit ? e => e.preventDefault() : undefined}
                onDragEnd={onDragEnd}
                onTouchStart={canEdit ? e => onTouchStart(e, idx) : undefined}
                onTouchMove={canEdit ? onTouchMove : undefined}
                onTouchEnd={canEdit ? e => onTouchEnd(e, idx) : undefined}
                style={{
                  background: dragOverIdx === idx && dragActiveIdx !== idx ? 'var(--hover)' : 'var(--surface)',
                  borderRadius: 12,
                  padding: '12px 14px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: 12,
                  boxShadow: 'var(--shadow-sm)',
                  opacity: dragActiveIdx === idx ? 0.35 : item.is_open ? 1 : 0.55,
                  cursor: canEdit ? 'grab' : 'default',
                  userSelect: 'none',
                  WebkitUserSelect: 'none',
                  transition: 'background 0.1s, opacity 0.1s',
                  borderTop: dragOverIdx === idx && dragActiveIdx !== idx ? '2px solid var(--accent)' : '2px solid transparent',
                }}
              >
                {/* Move up/down buttons */}
                {canEdit && (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 2, flexShrink: 0 }}>
                    <button onClick={() => moveItem(idx, -1)} disabled={idx === 0}
                      style={{ background: 'none', border: 'none', padding: '1px 4px', fontSize: 13, color: idx === 0 ? '#E5E7EB' : '#9CA3AF', cursor: idx === 0 ? 'default' : 'pointer', lineHeight: 1 }}>▲</button>
                    <button onClick={() => moveItem(idx, 1)} disabled={idx === items.length - 1}
                      style={{ background: 'none', border: 'none', padding: '1px 4px', fontSize: 13, color: idx === items.length - 1 ? '#E5E7EB' : '#9CA3AF', cursor: idx === items.length - 1 ? 'default' : 'pointer', lineHeight: 1 }}>▼</button>
                  </div>
                )}

                {/* Icon */}
                <div style={{
                  width: 44, height: 44, borderRadius: 10, background: getBg(item.name),
                  display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 22, flexShrink: 0,
                }}>
                  {getIcon(item.name)}
                </div>

                {/* Name + open/close badge */}
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontWeight: 700, fontSize: 15, color: 'var(--ink)', lineHeight: 1.3 }}>
                    {item.name}
                  </div>
                  <div style={{ marginTop: 4 }}>
                    {canEdit ? (
                      <button
                        onClick={() => toggleOpen(item)}
                        style={{
                          fontSize: 11, padding: '2px 8px', borderRadius: 20, border: 'none', cursor: 'pointer', fontWeight: 600,
                          background: item.is_open ? '#DCFCE7' : '#F3F4F6',
                          color: item.is_open ? '#166534' : '#6B7280',
                        }}
                      >
                        {item.is_open ? '● เปิดขาย' : '○ ปิดขาย'}
                      </button>
                    ) : (
                      <span style={{ fontSize: 11, color: item.is_open ? '#16A34A' : '#9CA3AF' }}>
                        {item.is_open ? '● เปิดขาย' : '○ ปิดขาย'}
                      </span>
                    )}
                  </div>
                </div>

                {/* Qty + Spoiled steppers */}
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4 }}>
                  {/* Main qty stepper */}
                  {canEdit ? (
                    <div style={{ display: 'flex', alignItems: 'center', gap: 0, background: '#F9F5F0', borderRadius: 10, padding: '2px' }}>
                      <button
                        onClick={() => adjustQty(item, -1)}
                        disabled={qty === 0 || isSaving}
                        style={{
                          width: 36, height: 36, border: 'none', background: qty === 0 ? 'transparent' : '#fff',
                          borderRadius: 8, fontSize: 20, cursor: qty === 0 ? 'not-allowed' : 'pointer',
                          color: qty === 0 ? '#D1D5DB' : '#DC2626', fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center',
                          boxShadow: qty === 0 ? 'none' : '0 1px 2px rgba(0,0,0,0.1)',
                        }}
                      >−</button>
                      <div style={{
                        width: 44, textAlign: 'center', fontWeight: 700, fontSize: 20,
                        color: qty > 0 ? '#166534' : '#9CA3AF',
                      }}>
                        {isSaving ? '…' : qty}
                      </div>
                      <button
                        onClick={() => adjustQty(item, +1)}
                        disabled={isSaving}
                        style={{
                          width: 36, height: 36, border: 'none', background: '#fff',
                          borderRadius: 8, fontSize: 20, cursor: 'pointer',
                          color: '#16A34A', fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center',
                          boxShadow: '0 1px 2px rgba(0,0,0,0.1)',
                        }}
                      >+</button>
                    </div>
                  ) : (
                    <div style={{ fontWeight: 700, fontSize: 24, minWidth: 36, textAlign: 'right', color: qty > 0 ? '#166534' : '#9CA3AF' }}>
                      {qty || '—'}
                    </div>
                  )}
                  {/* Spoiled counter */}
                  {canEdit ? (
                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 2 }}>
                      <div style={{ fontSize: 10, color: '#DC2626', fontWeight: 600, paddingRight: 2 }}>ของเสีย</div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 2, background: '#FEF2F2', borderRadius: 8, padding: '2px 4px' }}>
                      <button
                        onClick={() => adjustSpoiled(item, -1)}
                        disabled={spoiled === 0 || isSavingSpoiled}
                        style={{
                          width: 24, height: 24, border: 'none', background: spoiled === 0 ? 'transparent' : '#fff',
                          borderRadius: 6, fontSize: 15, cursor: spoiled === 0 ? 'not-allowed' : 'pointer',
                          color: spoiled === 0 ? '#FECACA' : '#DC2626', fontWeight: 700,
                          display: 'flex', alignItems: 'center', justifyContent: 'center',
                        }}
                      >−</button>
                      <div style={{ fontSize: 12, fontWeight: 700, color: spoiled > 0 ? '#DC2626' : '#FCA5A5', width: 40, textAlign: 'center' }}>
                        {isSavingSpoiled ? '…' : `🗑 ${spoiled}`}
                      </div>
                      <button
                        onClick={() => adjustSpoiled(item, +1)}
                        disabled={isSavingSpoiled}
                        style={{
                          width: 24, height: 24, border: 'none', background: '#fff',
                          borderRadius: 6, fontSize: 15, cursor: 'pointer',
                          color: '#DC2626', fontWeight: 700,
                          display: 'flex', alignItems: 'center', justifyContent: 'center',
                        }}
                      >+</button>
                    </div>
                    </div>
                  ) : (
                    spoiled > 0 && (
                      <div style={{ fontSize: 11, color: '#DC2626', fontWeight: 600 }}>🗑 เสีย {spoiled}</div>
                    )
                  )}
                </div>
                {/* Request delete */}
                {canEdit && (
                  <button onClick={() => setPendingDelete(item)}
                    style={{ background: 'none', border: 'none', fontSize: 16, color: '#D1C4B5', cursor: 'pointer', padding: '4px 2px', flexShrink: 0 }}
                    title="ขอลบรายการ">🗑</button>
                )}
              </div>

              {/* Spoiled details panel — shown when qty_spoiled > 0 */}
              {canEdit && spoiled > 0 && (
                <div style={{ marginTop: 6, padding: '10px 12px', background: '#FFF5F5', borderRadius: 10, border: '1px solid #FECACA' }}>
                  <div style={{ fontSize: 12, fontWeight: 700, color: '#B91C1C', marginBottom: 8 }}>
                    📋 ระบุสาเหตุขนมเสีย ({spoiled} ชิ้น)
                  </div>
                  {/* Reason chips */}
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 8 }}>
                    {SPOILED_REASONS.map(r => (
                      <button key={r.value}
                        onClick={() => setSpoiledDetails(prev => ({ ...prev, [item.id]: { ...prev[item.id], reason: r.value } }))}
                        style={{
                          padding: '5px 11px', borderRadius: 16, border: '1.5px solid',
                          borderColor: details.reason === r.value ? '#DC2626' : '#FECACA',
                          background: details.reason === r.value ? '#FEE2E2' : '#fff',
                          color: details.reason === r.value ? '#B91C1C' : '#9CA3AF',
                          fontSize: 12, fontWeight: details.reason === r.value ? 700 : 400,
                          cursor: 'pointer',
                        }}>
                        {r.label}
                      </button>
                    ))}
                  </div>
                  {/* Custom note when อื่นๆ selected */}
                  {details.reason === 'other' && (
                    <input
                      type="text"
                      placeholder="ระบุสาเหตุ..."
                      value={details.note || ''}
                      onChange={e => setSpoiledDetails(prev => ({ ...prev, [item.id]: { ...prev[item.id], note: e.target.value } }))}
                      style={{
                        width: '100%', boxSizing: 'border-box',
                        padding: '7px 10px', borderRadius: 8, border: '1.5px solid #FECACA',
                        fontSize: 13, fontFamily: 'inherit', marginBottom: 8,
                        outline: 'none', background: '#fff', color: '#1F2937',
                      }}
                    />
                  )}
                  {/* Photo */}
                  <input type="file" accept="image/*" capture="environment" id={photoInputId}
                    style={{ display: 'none' }}
                    onChange={e => {
                      const file = e.target.files[0];
                      if (!file) return;
                      const reader = new FileReader();
                      reader.onload = ev => setSpoiledDetails(prev => ({ ...prev, [item.id]: { ...prev[item.id], photo: ev.target.result } }));
                      reader.readAsDataURL(file);
                    }} />
                  {details.photo ? (
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <img src={details.photo} alt="waste" style={{ height: 52, width: 52, objectFit: 'cover', borderRadius: 8, border: '1px solid #FECACA' }} />
                      <button onClick={() => setSpoiledDetails(prev => ({ ...prev, [item.id]: { ...prev[item.id], photo: '' } }))}
                        style={{ fontSize: 12, color: '#DC2626', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 600 }}>
                        ✕ ลบรูป
                      </button>
                    </div>
                  ) : (
                    <label htmlFor={photoInputId} style={{
                      display: 'inline-flex', alignItems: 'center', gap: 6,
                      padding: '6px 12px', borderRadius: 8, border: '1.5px dashed #FECACA',
                      background: '#fff', color: '#DC2626', fontSize: 12, cursor: 'pointer', fontWeight: 600,
                    }}>
                      📷 ถ่ายรูปของเสีย
                    </label>
                  )}
                </div>
              )}
              </div>
            );
          })
        )}
      </div>

      {/* Request Delete Confirm Modal */}
      {pendingDelete && (
        <ModalOverlay onClose={() => setPendingDelete(null)}>
          <div style={{ padding: '20px 20px 16px' }}>
            <div style={{ fontWeight: 700, fontSize: 17, marginBottom: 8 }}>ขอลบรายการ</div>
            <div style={{ color: '#6B7280', fontSize: 14, marginBottom: 20 }}>
              ส่งคำขอลบ <strong>"{pendingDelete.name}"</strong> ให้แอดมินอนุมัติ?
            </div>
            <div style={{ display: 'flex', gap: 10 }}>
              <button onClick={() => setPendingDelete(null)}
                style={{ flex: 1, padding: 12, borderRadius: 10, border: '1.5px solid #E5E7EB', background: '#F9FAFB', cursor: 'pointer', fontSize: 15 }}>
                ยกเลิก
              </button>
              <button onClick={() => submitRequestDelete(pendingDelete)}
                style={{ flex: 1, padding: 12, borderRadius: 10, border: 'none', background: '#DC2626', color: '#fff', cursor: 'pointer', fontSize: 15, fontWeight: 700 }}>
                ขอลบ
              </button>
            </div>
          </div>
        </ModalOverlay>
      )}

      {/* Request Add Modal */}
      {showRequestAdd && (
        <ModalOverlay onClose={() => setShowRequestAdd(false)}>
          <div style={{ padding: '20px 20px 16px' }}>
            <div style={{ fontWeight: 700, fontSize: 17, marginBottom: 16 }}>ขอเพิ่มรายการขนม</div>

            {/* Suggestions from JE BAR menu */}
            {menuSuggestions.length > 0 && (() => {
              const existingNames = new Set(items.map(i => i.name));
              const suggestions = menuSuggestions.filter(n => !existingNames.has(n));
              return suggestions.length > 0 ? (
                <div style={{ marginBottom: 16 }}>
                  <div style={{ fontSize: 12, color: '#9CA3AF', marginBottom: 8 }}>จากเมนู JE BAR — แตะเพื่อเลือก</div>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                    {suggestions.map(name => (
                      <button key={name} onClick={() => setRequestName(name)}
                        style={{
                          padding: '6px 12px', borderRadius: 20,
                          border: `1.5px solid ${requestName === name ? 'var(--accent)' : 'var(--line)'}`,
                          background: requestName === name ? 'var(--accent)' : 'var(--bg)',
                          color: requestName === name ? '#fff' : 'var(--ink)',
                          fontSize: 13, cursor: 'pointer', fontFamily: 'inherit',
                        }}
                      >
                        {getIcon(name)} {name}
                      </button>
                    ))}
                  </div>
                </div>
              ) : null;
            })()}

            <input
              autoFocus
              value={requestName}
              onChange={e => setRequestName(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && submitRequestAdd()}
              placeholder="ชื่อรายการขนม เช่น เลมอนทาร์ต"
              style={{
                width: '100%', padding: '12px 14px', borderRadius: 10, border: '1.5px solid var(--line)',
                fontSize: 16, boxSizing: 'border-box', fontFamily: 'inherit',
              }}
            />
            <div style={{ fontSize: 12, color: 'var(--muted)', marginTop: 8 }}>
              คำขอจะส่งให้แอดมินอนุมัติก่อนแสดงในระบบ
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 16 }}>
              <button onClick={() => setShowRequestAdd(false)} style={{ flex: 1, padding: 12, borderRadius: 10, border: '1.5px solid var(--line)', background: 'var(--bg)', cursor: 'pointer', fontSize: 15 }}>
                ยกเลิก
              </button>
              <button
                onClick={submitRequestAdd}
                disabled={!requestName.trim() || requestSending}
                style={{ flex: 2, padding: 12, borderRadius: 10, border: 'none', background: 'var(--ink)', color: '#fff', cursor: 'pointer', fontSize: 15, fontWeight: 700, opacity: requestName.trim() ? 1 : 0.5 }}
              >
                {requestSending ? 'กำลังส่ง...' : 'ส่งคำขอ'}
              </button>
            </div>
          </div>
        </ModalOverlay>
      )}

      {/* History Modal */}
      {showHistory && (
        <ModalOverlay onClose={() => setShowHistory(false)}>
          <div style={{ padding: '16px 16px 8px', borderBottom: '1px solid var(--line)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <span style={{ fontWeight: 700, fontSize: 16 }}>ประวัติ 30 วัน</span>
            <button onClick={() => setShowHistory(false)} style={{ background: 'none', border: 'none', fontSize: 22, cursor: 'pointer', color: 'var(--muted)' }}>✕</button>
          </div>
          <div style={{ overflowY: 'auto', maxHeight: '65vh', padding: '8px 0' }}>
            {logsLoading ? (
              <div style={{ textAlign: 'center', padding: 32, color: 'var(--muted)' }}>กำลังโหลด...</div>
            ) : logs.length === 0 ? (
              <div style={{ textAlign: 'center', padding: 32, color: 'var(--muted)' }}>ยังไม่มีประวัติ</div>
            ) : (
              logs.map(log => (
                <div key={log.id} style={{ padding: '10px 16px', borderBottom: '1px solid var(--line-2)', display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                  <div style={{ fontSize: 18, flexShrink: 0 }}>{getIcon(log.item_name)}</div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--ink)' }}>{log.item_name}</div>
                    <div style={{ fontSize: 13, color: 'var(--muted)' }}>
                      {ACTION_LABELS[log.action] || log.action}
                      {log.action === 'adjust' && log.delta != null && (
                        <span style={{ marginLeft: 6, color: log.delta > 0 ? '#16A34A' : '#DC2626', fontWeight: 700 }}>
                          {log.delta > 0 ? `+${log.delta}` : log.delta} → {log.qty_after} ชิ้น
                        </span>
                      )}
                    </div>
                    <div style={{ fontSize: 11, color: 'var(--ink-3)', marginTop: 2 }}>
                      {log.emp_name} · {fmtTime(log.created_at)}
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </ModalOverlay>
      )}
    </div>
  );
}

// ─── ModalOverlay ─────────────────────────────────────────────────────────────
function ModalOverlay({ children, onClose }) {
  return (
    <div
      onClick={onClose}
      style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)', zIndex: 100, display: 'flex', alignItems: 'flex-end', justifyContent: 'center' }}
    >
      <div
        onClick={e => e.stopPropagation()}
        style={{ background: 'var(--surface)', borderRadius: '20px 20px 0 0', width: '100%', maxWidth: 520, animation: 'slideUp 0.2s ease' }}
      >
        {children}
      </div>
      <style>{`@keyframes slideUp { from { transform: translateY(100%) } to { transform: translateY(0) } }`}</style>
    </div>
  );
}
